language: node_js
node_js:
  - "node"

deploy:
  provider: npm
  email: joshkang@gmail.com
  api_key:
    secure: mDQiu45q6SvFd8yoJC2QLl5LzGSRyt2bNhQ4qnXEXHrQzS2OJ6rOHo4cDnftn175988OWdvfS0lotwmxHPNMlf2bAtt72GI27Qdo1nRqsqae4K2NBafi3lVCYRybH0i7qllz/+GRyCbgmS8I23uHAwHf9UIWY9vj0cvSXNtWIinfrPj/zGSr7G9kCTt9xcFeUvsjCDbVpR6E/2ToBg2yISmc3zW8qBHjPCbDOYOykiZuZ/6aj+GrfPP9VsjXmtdYrFnG9Xf4YJbyJVPU9dknmNVq7DDK7Lxjg9yOZoOcj7EbNJPHrjgpOsNyfZMvp25njkV30TowEius3am3oZuwvGg65bDCgUwUnVqpptYhFi6PEQNjHuKsBRcLnZj8KFtnsqWNwYfiibDe73v9zBQJgyq5wd1j/oaez80J0XLfjTDllBVztubhVaQp2BjxdATsS0SJl6Zx0Yv/WZZtS5DUcAbN7NgoHLRN1HlLwEbp+kE9B7JKw848VCMlUthH91iVp30Wbve25Sjw6ph1A4NDTlmqXnCjUyB9Pq4cVM8IwQxB6cjKGJl23k+7ia4Q+zD6WTwE5N/J9GNGjR7SFAwXseBESE8duXUT8MeVdB5zij/pMxCW6F7BBjOM7aiUvIEprKlJ/t4UnuziDYPeFXa3l8EC4hwQmhI419HEv924agc=
  on:
    branch: master
    tags: true
    repo: gfycat/gfycat-sdk
